/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.shop3d.admin.main;

import java.io.File;
import java.util.List;
import org.parse4j.ParseException;
import org.parse4j.ParseObject;
import org.parse4j.ParseQuery;
import org.parse4j.callback.FindCallback;
import org.shop3d.parse.ParseOperation;
import org.shop3d.server.main.ServerMain;
import org.shop3d.util.SharedData;

/**
 *
 * @author Fahad
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTabbedPane_UploadModel = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButton_PublishModel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField_UploadModelFilename = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_UploadModelTitle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_UploadModelTitle1 = new javax.swing.JTextField();
        jTextField_UploadModel_Image_0 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_UploadModel_Image_1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_UploadModel_Image_2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_UploadModel_Image_3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_UploadModel_Image_4 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField_UploadModelDir = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton_PublishModelDirectory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Output = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_PublishModel.setText("Publish to Parse");
        jButton_PublishModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PublishModelActionPerformed(evt);
            }
        });

        jLabel2.setText("Upload Model Filename:");

        jTextField_UploadModelFilename.setText("android");

        jLabel3.setText("Upload Model Title:");

        jTextField_UploadModelTitle.setText("Title");

        jLabel4.setText("Upload Model Description:");

        jTextField_UploadModelTitle1.setText("Description");

        jLabel5.setText("Image-0");

        jLabel6.setText("Image-1");

        jLabel7.setText("Image-2");

        jLabel8.setText("Image-3");

        jLabel9.setText("Image-4");

        jTextField_UploadModelDir.setText("C:\\Users\\Fahad\\Documents\\NetBeansProjects\\Shop3DAdming\\Models\\");

            jLabel10.setText("Upload MODEL Directory:");

            jButton_PublishModelDirectory.setText("Publish All Models in DIR to Parse");
            jButton_PublishModelDirectory.setActionCommand("JButton_");
            jButton_PublishModelDirectory.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_PublishModelDirectoryActionPerformed(evt);
                }
            });

            jTextArea_Output.setColumns(20);
            jTextArea_Output.setRows(5);
            jScrollPane1.setViewportView(jTextArea_Output);

            jLabel11.setText("Output");

            jButton2.setText("Test");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            jButton1.setText("Clear Output");

            jButton3.setText("Fix Category Count");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });

            jButton4.setText("Clear All Model Data");
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
                }
            });

            jLabel12.setText("THIS IS DORPBOX/SERVER/SYNC");

            jButton5.setText("Create Sales Count Record");
            jButton5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton5ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(29, 29, 29)
                            .addComponent(jTextField_UploadModelDir)
                            .addContainerGap())
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField_UploadModelTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField_UploadModelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField_UploadModel_Image_0, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField_UploadModel_Image_1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField_UploadModel_Image_2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField_UploadModel_Image_3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField_UploadModel_Image_4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton2)
                                            .addGap(60, 60, 60))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(74, 74, 74)
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel2)
                                                    .addGap(29, 29, 29)
                                                    .addComponent(jTextField_UploadModelFilename, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton5))
                                        .addComponent(jButton_PublishModel))
                                    .addGap(18, 18, 18)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(55, 55, 55))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jButton_PublishModelDirectory)
                            .addGap(107, 107, 107)
                            .addComponent(jButton4)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11)
                                    .addGap(80, 80, 80))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addComponent(jButton3))))))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jTextField_UploadModelDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel11))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_PublishModelDirectory)
                                    .addComponent(jButton3))
                                .addComponent(jButton4))
                            .addGap(0, 4, Short.MAX_VALUE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jTextField_UploadModelFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jTextField_UploadModelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jTextField_UploadModelTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jTextField_UploadModel_Image_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField_UploadModel_Image_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jTextField_UploadModel_Image_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8)
                                        .addComponent(jTextField_UploadModel_Image_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel9))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(jButton5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField_UploadModel_Image_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2))))
                            .addGap(24, 24, 24))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton_PublishModel)
                        .addComponent(jButton1))
                    .addGap(22, 22, 22))
            );

            jTabbedPane_UploadModel.addTab("Upload Model", jPanel2);

            jLabel1.setText("jLabel1");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(804, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(410, Short.MAX_VALUE))
            );

            jTabbedPane_UploadModel.addTab("tab1", jPanel1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane_UploadModel)
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane_UploadModel, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(88, Short.MAX_VALUE))
            );

            jTabbedPane_UploadModel.getAccessibleContext().setAccessibleName("tab_mtl_manager");
            jTabbedPane_UploadModel.getAccessibleContext().setAccessibleDescription("");

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton_PublishModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PublishModelActionPerformed
        /*
         Req_GetMaterials allMaterials = new Req_GetMaterials(Req_Base.RunMode.PRODUCTION);
         allMaterials.SendPostRequest();
         int y = 0;
        
         try{

         File[] directories = new File(SharedData.RootModelStoragePath).listFiles(File::isDirectory);
            
         // ParseOperation.UploadModel("android");
          
          
         }catch(Exception er) {
         System.out.println(" CANNOT UPLOAD MODEL: EXCDEPTION --- " + jTextField_UploadModelFilename.getText());
         System.out.println(er.getMessage());
         }          */
    }//GEN-LAST:event_jButton_PublishModelActionPerformed

    private void jButton_PublishModelDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PublishModelDirectoryActionPerformed

        String globalDir = jTextField_UploadModelDir.getText();
        File[] directories = new File(globalDir).listFiles();

        // File[] directories = new File(globalDir).listFiles(File::isDirectory);
        for (int i = 0; i < directories.length; i++) {

            if (directories[i].isDirectory()) {
                jTextArea_Output.append(i + 1 + ". Saving: " + directories[i].getName() + "\n");
                String individualModelDir = globalDir + directories[i].getName() + "\\";

                // Input the individual model directory and the name of the model directory.
                // the name of the obj and mtl file are the same
                ParseOperation.UploadModel(individualModelDir);
                jTextArea_Output.append("  --- completed --- \n");
            }
        }
        ParseOperation.UpdateCategoryCount();


    }//GEN-LAST:event_jButton_PublishModelDirectoryActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.out.println("Nothing happened, you pressed TEST button.");
        /*
         //Req_DesignUpload uploadModel = new Req_DesignUpload(Req_Base.RunMode.TEST);
         // uploadModel.SendPostRequest();
         WavefrontObject mtlObj = new WavefrontObject("C:\\Users\\Fahad\\Documents\\NetBeansProjects\\Shop3DAdming\\Models\\android\\android.obj");
         Hashtable<String, Material> myMat = mtlObj.getMaterials();

         String mtlNames = "";
         String mtlRGB = "";
         String mtlOrder = "";
         int counter = 0;
         Enumeration e = myMat.keys();
         while (e.hasMoreElements()) {
         String actualMtlName = e.nextElement().toString();

            
         if (actualMtlName.contains("X_")) {
         Material thisMat = myMat.get(actualMtlName);
         String RGB = Util.FormatDouble(thisMat.getKd().getX(), 2) + ":"
         + Util.FormatDouble(thisMat.getKd().getY(), 2) + ":"
         + Util.FormatDouble(thisMat.getKd().getZ(), 2) + ":";
                
         String [] tokens = actualMtlName.split("_");
         if (mtlNames.equals("")) {
         mtlNames = tokens[1];
         mtlRGB = RGB;
         mtlOrder = counter + "";
         } else {
         mtlNames += "*" + tokens[1];
         mtlRGB += "*" + RGB;
         mtlOrder += "*" + counter;
         }
         counter ++;

         }
         } // End of all hashtable items
        
         // completedDBEntry.put("mtl_names", mtlNames);
         // completedDBEntry.put("mtl_display_names", mtlNames);
         // completedDBEntry.put("mtl_colors", mtlRGB);
         // completedDBEntry.put("mtl_order", mtlOrder);
         // completedDBEntry.put("mtl_display_order", mtlOrder);
         */
        //mtlObj.parse("C:\\Users\\Fahad\\Documents\\NetBeansProjects\\Shop3DAdming\\Models\\android\\android.obj");
        int y = 0;

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ParseOperation.UpdateCategoryCount();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        // TODO add your handling code here:
        ParseOperation.ClearAll("Model");
        ParseOperation.ClearAll("Favorite");
        ParseOperation.ClearAll("Model_UserMade");
        ParseOperation.ClearAll("Order");
        ParseOperation.ClearAll("Order_Item");
        ParseOperation.ClearAll("Sales_Model_Count");
        // Clear the Sales_Order_Count table
        // Get that particular date object.
        ParseQuery<ParseObject> computeQuery = ParseQuery.getQuery("Sales_Order_Count");
        computeQuery.whereNotEqualTo("order_count", 0);

        try {
            List<ParseObject> list = computeQuery.find();
            if (list != null) {
                for (int i = 0; i < list.size(); i++) {
                    list.get(0).put("order_count", 0);
                    list.get(0).put("order_item_count", 0);
                    list.get(0).put("order_item_type_count", 0);
                    list.get(0).put("total_stripe_charge_amount", 0);
                    list.get(0).put("total_profit_amount", 0);
                    list.get(0).put("total_sculpteo_cost_amount", 0);
                    list.get(0).put("total_cc_cost_amount", 0);
                    list.get(0).save();
                }
            }
        } catch (Exception er) {
            jTextArea_Output.append("Error in clearing Sales_Order_Count stuff \n");
        }
        jTextArea_Output.append(" ALL MODEL DATA RESET  \n");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      // JUST SO YOU DONT ACCIDENTALLY CREATE MORE
        //  ParseOperation.CreateSalesCountRecord();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        ParseOperation.IniParse();

        // Ubuntu always runs in servermode and the log etc paths are different.
        SharedData.FixFolderPaths();

        if (SharedData.SERVER_MODE) {
            System.out.println("Server mode is running.");
            ServerMain.start();

        } else {
            try {
                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new Dashboard().setVisible(true);
                    }
                });
            } catch (Exception er) {
                System.out.println(" Error, from main");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton_PublishModel;
    private javax.swing.JButton jButton_PublishModelDirectory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane_UploadModel;
    private javax.swing.JTextArea jTextArea_Output;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_UploadModelDir;
    private javax.swing.JTextField jTextField_UploadModelFilename;
    private javax.swing.JTextField jTextField_UploadModelTitle;
    private javax.swing.JTextField jTextField_UploadModelTitle1;
    private javax.swing.JTextField jTextField_UploadModel_Image_0;
    private javax.swing.JTextField jTextField_UploadModel_Image_1;
    private javax.swing.JTextField jTextField_UploadModel_Image_2;
    private javax.swing.JTextField jTextField_UploadModel_Image_3;
    private javax.swing.JTextField jTextField_UploadModel_Image_4;
    // End of variables declaration//GEN-END:variables
}
